MvcCarRental/CarRental/CarRental/Models/Entity/Rental.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarRental.Models.Entity
{
    public class Rental
    {
        public int RentalId { get; set; }

        [Required]
        public DateTime RentalDate { get; set; }

        [Required]
        public DateTime ReturnDate { get; set; }
        public int CustomerId { get; set; }
        public int CarId { get; set; }

        public Car Car { get; set; }
        public Customer Customer { get; set; }
    }
}

MvcCarRental/CarRental/CarRental/Controllers/RentalController.cs
using CarRental.Models;
using CarRental.Models.Context;
using CarRental.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace CarRental.Controllers
{
    public class RentalController : Controller
    {
        CRDbContext db = new CRDbContext();
        // GET: Rental
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Customer customer)
        {
            RentalWizardModel RentalWizard = new RentalWizardModel();
            RentalWizard.Customer = customer;
            Session["RentalWizard"] = RentalWizard;

            return RedirectToAction("AddLicense");
        }

        public ActionResult CarSelection()
        {
            var modelOfBrands = new Dictionary<Brand, List<Model>>();
            var brand = db.Brand.ToList();

            foreach (var item in brand)
            {
                modelOfBrands.Add(item, (from m in db.Model
                                         where m.BrandId == item.BrandId
                                         select m).ToList());
            }
            ViewBag.ModelOfBrands = modelOfBrands;

            return View();
        }

        [HttpPost]
        public ActionResult CarSelection(RentalWizardModel rentalWizard)
        {
            var sessionRentalWizar = ((RentalWizardModel)Session["RentalWizard"]);
            sessionRentalWizar.Car = db.Car.FirstOrDefault(c => c.CarId == rentalWizard.Car.CarId);

            return RedirectToAction("DateSelection");
        }

        [HttpGet]
        public ActionResult DateSelection()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DateSelection(Rental rental)
        {
            var sessionRentalWizar = ((RentalWizardModel)Session["RentalWizard"]);
            rental.CarId = sessionRentalWizar.Car.CarId;

            SaveDrivingLicenseToDb(sessionRentalWizar.DrivingLicense);

            sessionRentalWizar.Customer.DrivingLicenseId = db.DrivingLicense.ToList().Last().DrivingLicenseId;
            SaveCustomerToDb(sessionRentalWizar.Customer);

            rental.CustomerId = db.Customer.ToList().Last().CustomerId;
            SaveRentalToDb(rental);

            TempData["Message"] = "Kiralama işlemi başarılı bir şekilde gerçekleştirildi.";


            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult AddLicense()
        {
            ViewBag.LicenseTypeList = Enum.GetNames(typeof(LicenseType));

            return View();
        }

        [HttpPost]
        public ActionResult AddLicense(DrivingLicense drivingLicense)
        {
            ((RentalWizardModel)Session["RentalWizard"]).DrivingLicense = drivingLicense;
            return RedirectToAction("CarSelection");
        }


        [HttpGet]
        public JsonResult GetCars(int? modelId)
        {
            var cars = (from car in db.Car.ToList()
                        where car.ModelId == modelId
                        select car).ToList();

            var carList = new List<Car>();
            var availableList = new List<string>();
            foreach (var item in cars)
            {
                var rental = (from r in db.Rental.ToList()
                              where r.CarId == item.CarId
                              select r).ToList();

                carList.Add(item);
                availableList.Add(IsAvailable(rental) ? "true" : "false");
            }
            var result = new { Cars = carList, Availables = availableList };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public bool IsAvailable(List<Rental> rentals)
        {
            foreach (var rental in rentals)
            {
                if (rental != null && rental.ReturnDate >= DateTime.Now)
                {
                    return false;
                }
            }

            return true;
        }

        public ActionResult CurrentRentals()
        {
            return View(db.Rental.Include("Customer").Include("Car").Include("Car.Model").ToList());
        }

        [HttpGet]
        public ActionResult Messages()
        {
            var lastDayRental = db.Rental
                .Include("Car")
                .Include("Customer")
                .Include("Car.Model")
                .Include("Car.Model.Brand")
                .Where(r => r.ReturnDate == DateTime.Today).ToList();

            return PartialView("_Messages", lastDayRental);
        }

        //Private Parts
        private void SaveRentalToDb(Rental rental)
        {
            db.Rental.Add(rental);
            db.SaveChanges();
        }

        private void SaveCustomerToDb(Customer customer)
        {
            customer.Cars = null;
            customer.DrivingLicense = null;
            db.Entry(customer).State = System.Data.Entity.EntityState.Added;
            //db.Customer.Add(customer);
            db.SaveChanges();
        }

        private void SaveDrivingLicenseToDb(DrivingLicense drivingLicense)
        {
            db.DrivingLicense.Add(drivingLicense);
            db.SaveChanges();
        }
    }
}

MvcCarRental/CarRental/CarRental/Views/Rental/AddLicense.cshtml
@model CarRental.Models.Entity.DrivingLicense
@{
    ViewBag.Title = "AddLicense";
}

<div class="container-fluid">
    <h1 class="h-3 text-center p-3">Ehliyet Ekleme</h1>
    @using (Html.BeginForm("AddLicense", "Rental", FormMethod.Post, new { @class = "w-100" }))
    {
        <div class="row justify-content-center">
            <table class="table w-50">
                <tr>
                    <td>@Html.LabelFor(d => d.LicenseNumber, "Ehliyet Numarası")</td>
                    <td>@Html.TextBoxFor(d => d.LicenseNumber, new { @class = "form-control", type = "number", required = "required" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(d => d.DateOfIssue, "Veriliş Tarihi")</td>
                    <td>@Html.TextBoxFor(d => d.DateOfIssue, new { @class = "form-control", type = "date", required = "required" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(d => d.LicenseType, "Ehliyet Türü")</td>
                    <td>@Html.DropDownListFor(d => d.LicenseType, new SelectList(ViewBag.LicenseTypeList), new { @class = "dropdown pt-0 pb-0 form-control", required = "required" })</td>
                </tr>
            </table>
        </div>
        <div class="row d-flex justify-content-around">
            @Html.ActionLink("Geri", "Index", null, new { @class = "btn btn-secondary" })
            <button type="submit" class="btn btn-secondary">İleri</button>
        </div>

    }
</div>

MvcCarRental/CarRental/CarRental/Views/Rental/CarSelection.cshtml
@using CarRental.Models.Entity;
@model CarRental.Models.Entity.RentalWizardModel

@{
    ViewBag.Title = "CarSelection";
}

<script src="~/Assets/js/myScripts.js"></script>

<div class="container-fluid">
    <h1 class="h3 text-center">Araç Seçimi</h1>
    <div>
        <div class="row">
            <table class="table table-responsive">
                <tr>
                    <td>@Html.LabelFor(r => r.Brand.BrandId, "Marka")</td>
                    <td style="width:150px;">@Html.DropDownListFor(r => r.Brand.BrandId, new SelectList(ViewBag.ModelOfBrands.Keys, "BrandId", "Name"), new { @class = "form-control dropdown-brand pt-0 pb-0", required = "required" })</td>

                    <td>@Html.LabelFor(c => c.Model.ModelId, "Model")</td>
                    <td style="width:150px;">
                        @Html.DropDownListFor(c => c.Model.ModelId, new SelectList(""), new { @class = "form-control dropdown-model pt-0 pb-0", required = "required" })
                    </td>
                </tr>
            </table>
        </div>
        <div class="row">
            @using (Html.BeginForm("CarSelection", "Rental", FormMethod.Post))
            {
                <table id="car_display_table" class="table table-responsive col-md-11">
                    <thead>
                        <tr>
                            <th>Renk</th>
                            <th>Plaka</th>
                            <th>Günlük Ücret</th>
                            <th>Trafiğe Çıkış Tarihi</th>
                            <th>Motor Hacmi</th>
                            <th>Motor Gücü</th>
                            <th>Vites Türü</th>
                            <th>Kasa Tipi</th>
                            <th>Yakıt Türü</th>
                            <th>Koltuk Sayısı</th>
                            <th>Yaş Limiti</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>

                @Html.ActionLink("Geri", "AddLicense", null, new { @class = "btn btn-secondary w-25" })
                <button type="submit" class="btn btn-secondary float-right w-25">İleri</button>
            }
        </div>
    </div>
</div>

<script>

    @{
            var modelOfBrands = (Dictionary<Brand, List<Model>>) ViewBag.ModelOfBrands;
        }

    var models = {
        @foreach (var carModelPair in modelOfBrands)
        {
            @:'@carModelPair.Key.BrandId': [
            foreach (var carModel in carModelPair.Value)
            {
                @:{ Id: @carModel.ModelId, Name: '@carModel.Name' },
            }
            @:],
        }
    }

    $('select.dropdown-brand').change(function () {
        var brandId = $(this).val();
        var modelsOfBrand = models[brandId];
        $('select.dropdown-model').empty();
        for (var i = 0; i < modelsOfBrand.length; i++) {
            $('select.dropdown-model').append($('<option>').val(modelsOfBrand[i].Id).append(modelsOfBrand[i].Name));
        }
    })

    $('select.dropdown-model').change(function () {
        var modelId = $(this).val();
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetCars", "Rental")',
            data: { modelId: modelId },
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: DisplayReceivedCars
        })
    })

    function DisplayReceivedCars(data) {
        debugger;
        var carList = [];
        var carAvailableList = [];

        $.each(data, function (index, item) {
            if (index == "Cars") {
                carList = item;
            } else {
                carAvailableList = item;
            }
        })
        $('#car_display_table > tbody').empty();
        var rowId = 0;
        $.each(carAvailableList, function (index, isAvailable) {
            if (isAvailable == 'true') {
                var tr = $('<tr>');
                tr.attr('id', rowId.toString());
                rowId++;
                $.each(carList[index], function (count, item) {
                    if (count!='CarId' && count!= 'ModelId') {
                        var td = $('<td>');
                        td.append(item);
                        tr.append(td);
                    }
                })
                var tdForRadioButton = $('<td>');
                var radioButton = $('@Html.RadioButtonFor(r => r.Car.CarId, "",new {required = "required" })');
                radioButton.attr('id', 'CarId');
                radioButton.attr('value', carList[index].CarId);
                tdForRadioButton.append(radioButton);
                tr.append(tdForRadioButton);
                $('#car_display_table > tbody').append(tr);
            }
        })
    }
</script>

MvcCarRental/CarRental/CarRental/Views/Rental/CurrentRentals.cshtml
@model List<CarRental.Models.Entity.Rental>
@{
    ViewBag.Title = "CurrentRentals";
}


<div class=" align-items-center pt-3 pb-2 mb-3 border-bottom">
    <div class="d-flex flex-wrap p-3 justify-content-center">
        <h1 class="h2">Mevcut Kiralama Listesi</h1>
    </div>

    <div class="table-responsive">
        <table class="table table-dark table-striped table-sm">
            <thead>
                <tr>
                    <th>İsim</th>
                    <th>Soyisim</th>
                    <th>Müşteri Kimlik No</th>
                    <th>Model</th>
                    <th>Plaka</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Customer.FirstName</td>
                        <td>@item.Customer.LastName</td>
                        <td>@item.Customer.IdentityNumber</td>
                        <td>@item.Car.Model.Name</td>
                        <td>@item.Car.PlateNumber</td>
                        <td>
                            <a href="@Url.Action("Edit",new { id=item.RentalId})"><i class="fas fa-edit"></i></a>
                        </td>
                        <td>
                            <a href="@Url.Action("Delete", new { id=item.RentalId})"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

MvcCarRental/CarRental/CarRental/Views/Rental/DateSelection.cshtml
@model CarRental.Models.Entity.Rental
@{
    ViewBag.Title = "DateSelection";
}

<div class="container-fluid">
    <h1 class="h3 text-center">Tarih Seçimi</h1>
    <div>
        <div class="row">
            @using (Html.BeginForm("DateSelection", "Rental", FormMethod.Post))
            {
                <table class="table table-responsive">
                    <tr>
                        <td>@Html.LabelFor(r => r.RentalDate, "Kiralama Tarihi")</td>
                        <td>@Html.TextBoxFor(r => r.RentalDate, new { @class = "form-control", type = "date", required = "required" })</td>
                    </tr>
                    <tr>
                        <td>@Html.LabelFor(r => r.ReturnDate, "Teslim Tarihi")</td>
                        <td>@Html.TextBoxFor(r => r.ReturnDate, new { @class = "form-control", type = "date", required = "required" })</td>
                    </tr>
                </table>
                @Html.ActionLink("Geri", "CarSelection", null, new { @class = "btn btn-secondary" })
                <button type="submit" class="btn btn-secondary float-right">Kiralama Oluştur</button>
            }
        </div>
    </div>
</div>

MvcCarRental/CarRental/CarRental/Views/Rental/Index.cshtml
@model CarRental.Models.Entity.Customer
@{
    ViewBag.Title = "NewRental";
}

<div class="container-fluid">
    <h1 class=" h-3 text-center">Yeni Kiralama</h1>
    <div class="row">
        @using (Html.BeginForm("Index", "Rental", FormMethod.Post, new { @class = "d-flex w-100" }))
        {
            <div class="col-12 col-lg-6">
                <table class="table">
                    <tr>
                        <td>@Html.LabelFor(c => c.FirstName, "Ad")</td>
                        <td>@Html.TextBoxFor(c => c.FirstName, new { @class = "form-control", @name="firstName" , required="required"})</td>
                    </tr>
                    <tr>
                        <td>@Html.LabelFor(c => c.LastName, "Soyad")</td>
                        <td>@Html.TextBoxFor(c => c.LastName, new { @class = "form-control" })</td>

                    </tr>
                    <tr>
                        <td>@Html.LabelFor(c => c.IdentityNumber, "Kimlik Numarası")</td>
                        <td>@Html.TextBoxFor(c => c.IdentityNumber, new { @class = "form-control", type = "number" })</td>
                    </tr>
                    <tr>
                        <td>@Html.LabelFor(c => c.DateOfBirth, "Doğum Tarihi")</td>
                        <td>@Html.TextBoxFor(c => c.DateOfBirth, new { @class = "form-control", type = "date" })</td>
                    </tr>
                </table>
            </div>
            <div class="col-12 col-lg-6">
                <table class="table">
                    <tr>
                        <td>@Html.LabelFor(c => c.PhoneNumber, "Telefon Numarası")</td>
                        <td>@Html.TextBoxFor(c => c.PhoneNumber, new { @class = "form-control telephon" })</td>
                    </tr>
                    <tr>
                        <td>@Html.LabelFor(c => c.Email, "E-Posta Adresi")</td>
                        <td>@Html.TextBoxFor(c => c.Email, new { @class = "form-control email" })</td>
                    </tr>
                    <tr>
                        <td>@Html.LabelFor(c => c.Address, "Adres")</td>
                        <td>@Html.TextAreaFor(c => c.Address, new { @class = "form-control" })</td>
                    </tr>
                </table>
                <button type="submit" class="btn btn-secondary float-right w-25"><strong>İleri</strong></button>
            </div>
        }
    </div>
</div>